window.echo_list = [
    "Dress",
    "Dancing With Our Hands Tied",
    "Call It What You Want",
    "I Think He Knows",
    "Labyrinth",
    "Snow On The Beach (feat. Lana Del Rey)",
    "Lavender Haze",
    "Paris",
    "cardigan",
    "illicit affairs",
    "Style (Taylor's Version)",
    "Paper Rings",
    "Mastermind",
    "invisible string",
    "You Are In Love (Taylor's Version)",
    "Jump Then Fall (Taylor’s Version)",
    "The Very First Night (Taylor's Version) (From The Vault)",
    "Message In A Bottle (Taylor's Version) (From The Vault)",
    "Sweet Nothing",
    "Daylight - Live From Paris",
    "Come Back...Be Here (Taylor's Version)",
    "Everything Has Changed (feat. Ed Sheeran) (Taylor’s Version)",
    "Fearless (Taylor’s Version)",
    "The Great War",
    "Enchanted (Taylor's Version)",
    "Out Of The Woods (Taylor's Version)",
    "State Of Grace (Taylor's Version)",
    "Untouchable (Taylor’s Version)",
    "Stay Stay Stay (Taylor's Version)",
    "King Of My Heart",
    "this is me trying",
    "Gorgeous",
    "Sparks Fly (Taylor’s Version)",
    "I Know Places (Taylor's Version)",
    "the lakes - bonus track",
    "Mine (Taylor's Version)",
    "Last Kiss (Taylor's Version)",
    "New Year’s Day",
    "False God",
    "cowboy like me",
    "peace",
    "Glitch",
    "It’s Nice To Have A Friend",
    "I Almost Do (Taylor's Version)",
    "Cruel Summer",
    "Bigger Than The Whole Sky",
    "Cornelia Street",
    "gold rush",
    "Ours (Taylor’s Version)",
    "Afterglow",
    "Treacherous (Taylor's Version)",
    "Holy Ground (Taylor's Version)",
    "Love Story (Taylor’s Version)",
    "Lover - Live From Paris",
    "willow",
    "Don’t Blame Me",
    "Delicate",
    "Wildest Dreams (Taylor's Version)",
    "Forever Winter (Taylor's Version) (From The Vault)",
    "This Love (Taylor’s Version)",
    "The Story Of Us (Taylor's Version)",
    "Miss Americana & The Heartbreak Prince",
    "The Archer",
    "We Were Happy (Taylor’s Version) (From The Vault)",
    "I'm Only Me When I'm With You",
    "So It Goes...",
    "Eyes Open (Taylor's Version)",
    "I Don’t Wanna Live Forever (Fifty Shades Darker)",
    "Our Song",
    "I Can See You (Taylor’s Version) (From The Vault)",
    "Timeless (Taylor’s Version) (From The Vault)",
    "You Belong With Me (Taylor’s Version)",
    "End Game",
    "...Ready For It?",
    "Red (Taylor's Version)",
    "Drops Of Jupiter - Live/2011",
    "Slut! (Taylor's Version) (From The Vault)",
    "The Other Side Of The Door (Taylor’s Version)",
    "Suburban Legends (Taylor's Version) (From The Vault)",
    "Guilty as Sin?",
    "But Daddy I Love Him",
    "The Tortured Poets Department",
    "The Alchemy",
    "So High School",
    "Down Bad",
    "Mary's Song (Oh My My My)",
    "ME! (feat. Brendon Urie of Panic! At The Disco)"
];
